config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"

  # get "cocktails/:id", to: "cocktails#show", as: :cocktail
  resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
    resources :doses, only: [:create]
    resources :reviews, only: [:create]
  end
  resources :search, only: [:index]
  resources :doses, only: [:destroy]
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [ :name ],
    using: {
    tsearch: { prefix: true }
    }

  has_one_attached :photo
  has_many :reviews, dependent: :destroy
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, :description, :photo, presence: true
  validates :name, uniqueness: true
  
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, :cocktail_id, :ingredient_id, presence: true
  # validates :cocktail_id, :ingredient_id, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true
  validates :name, uniqueness: true

  # include PgSearch::Model
  # multisearchable against: [:name]
    # using: {
    # tsearch: { prefix: true }
    # }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :comment, presence: true
  validates :rating, numericality: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
    if params[:query].present?
      @cocktails = Cocktail.search_by_name(params[:query])
    else
      @cocktails = Cocktail.all
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # def new
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   @dose = Dose.new
  # end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @review = Review.new
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new
      @review = Review.new
      render "cocktails/show"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to cocktail_path(@review.cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.6)), url(https://res.cloudinary.com/deyqjsowe/image/upload/v1589527146/adam-wilson-6UIonphZA5o-unsplash_vk4ts6.jpg);">
  <div class="container">
    <h1><strong>Cocktail Recipes</strong></h1>
    <p>Organize your favorite cocktail recipes.</p>
    <%= link_to "Create a New Recipe", new_cocktail_path, class:"btn btn-cocktail" %>
  </div>
</div>

<div class="cocktail-cards container">
  <% @cocktails.each do |cocktail| %>
  <div class="card-trip">
    <%= image_tag cocktail.photo, alt: "alttext" %>
    <div class="card-trip-infos">
      <div>
        <h2><%= cocktail.name %></h2>
        <p><%= cocktail.description %></p>
      </div>
    </div>
    <div class="center-button">
              <%= link_to "See Details", cocktail_path(cocktail), class: "btn btn-cocktail"  %>
    </div>
  </div>
  <% end %>
</div>

<!-- 
      <%# unless cocktail.reviews == [] %>
      <h6 class="text-center"><%#= cocktail.reviews.first.rating %></h6>
        <i class="far fa-star"></i>
      <%# else %>
      <h6 class="text-center">No Ratings Available</h6>
      <%# end %> -->

app/views/cocktails/new.html.erb
<div class="banner-new-cocktail" style="background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.75)), url(https://res.cloudinary.com/deyqjsowe/image/upload/v1589527146/adam-wilson-6UIonphZA5o-unsplash_vk4ts6.jpg);">
  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-2"></div>
      <div class="col-12 col-lg-8 form-over-banner">
        <h4 class="yellow-font bold-font text-center my-3">Add a New Cocktail</h4>
        <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name,  class:"yellow-font", label: "Name of New Cocktail" %>
          <%= f.input :description, label: "Cocktail Description" %>
          <%#= f.input :photo, as: :file, label: "Upload a Photo", input_html: { class: 'hidden'} %>
          <%= f.input :photo, input_html: { class: 'd-none' }, label_html: { class: 'my-3 btn upload-photo'}, label: 'Upload a Photo' %>

          <%#= f.input :photo, as: :file %>
          <%= f.button :submit, class: 'btn btn-cocktail' %>
        <% end %>
      </div>
      <div class="col-12 col-lg-2"></div>
    </div>


  </div>
</div>

  

app/views/cocktails/show.html.erb
<div class="container my-3">
  
  <div class="">
    <div class="row">
      <div class="col-12 col-lg-5 photo-and-description-div">
        <div class="name">
          <h1 class="yellow-font bold-font"><%= @cocktail.name %></h1>
        </div>
        <%= image_tag @cocktail.photo, class: "resized-photo", alt: "photo of cocktail" %>
        <h5 class="yellow-font my-3 text-center"><%= @cocktail.description %></h5>
        <div class="text-center">
          <%= link_to "Delete this Cocktail", cocktail_path(@cocktail), method: :delete,  class:"btn btn-cocktail", data: { confirm: "Are you sure?" } %>
        </div>  
      </div>

      <div class="col-12 col-lg-7 ingredients-div">
        <h4 class="yellow-font bold-font text-center ingredient-h4">Ingredients</h4>
        <% @cocktail.doses.each do |dose| %>
        <div class="d-flex justify-content-between lighter-background m-3">
            <div><h6 class="yellow-font m-3"><%= dose.ingredient.name %>&nbsp;&nbsp;&nbsp;&nbsp; (<%= dose.description %>)</h6></div>
            <div><%= link_to dose_path(dose), method: :delete,  class:"", data: { confirm: "Are you sure?" } do %>
              <i class="fas fa-minus-circle yellow-font m-3"></i>
              <% end %>
            </div>  
        </div>
        <% end %>
        <div class="mx-3 ingredients-form">
          <%= render "doses/new", cocktail: @cocktail, dose: @dose %>
        </div>
      </div>
    </div>
  </div>

  <div class="">
    <div class="row">
      <div class="col-12 col-lg-2"></div>
      <div class="col-12 col-lg-8 reviews-div">
        <div>
          <h4 class="yellow-font bold-font text-center ingredient-h4">Comments & Reviews</h4>
        <% @cocktail.reviews.each do |review| %>
        <div class="d-flex justify-content-center m-3 darker-background">
            <div><h4 class="yellow-font m-3"><%= review.comment %></h4></div>
            <%= link_to review_path(review),  class:"yellow-font m-3", method: :delete, data: { confirm: "Are you sure?" } do %>
              <i class="fas fa-minus-circle yellow-font"></i>
            <% end %>
        </div>
        <% end %>
        </div>

       <div class="my-3">
          <%= render "reviews/new", cocktail: @cocktail, review: @review %>
        </div>
      </div>
      <div class="col-12 col-lg-2"></div>
    </div>
</div>

app/views/doses/_new.html.erb
<h4 class="yellow-font bold-font text-center ">Add an Ingredient</h4>

<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown, select2 form-control" }, include_hidden: false, collection: Ingredient.order('name ASC') %>
  <%= f.input :description, class: "label form-control", label: "How much?" %>
  <%= f.button :submit, 'Add this Ingredient', class: 'btn btn-cocktail' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Rails Cocktail Recipes</title>
    <link rel="shortcut icon" type="image/jpg" href="https://res.cloudinary.com/deyqjsowe/image/upload/v1592208600/Photography_qtz3tc.png"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="cocktail-navbar">
      <div>
        <%= link_to root_path do %>
          <%= image_tag "https://res.cloudinary.com/deyqjsowe/image/upload/v1592208600/Photography_qtz3tc.png", class: "cocktail-logo" %>
        <% end %>
      </div>
          <!-- SEARCH BAR WILL GO HERE with no margins or padding...-->
      <div>
        <%= form_tag cocktails_path, class: "", method: :get do %>
        <div class="d-flex">
          <%= text_field_tag :query,
            params[:query],
            class: "nav-search-field", placeholder: "Find a Cocktail" %>
          <%= submit_tag "Search", class: "btn btn-cocktail-search" %>
        <% end %>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/reviews/_new.html.erb
<h4 class="yellow-font bold-font text-center review-form-margin">Write a Comment or Review About this Cocktail</h4>

<%= simple_form_for [cocktail, review] do |f| %>
  <%#= f.input :rating, collection: 0..5 %>
  <%#= f.input :rating, input_html: { min: '0', step: '1' } %>

  <%= f.input :comment, class: "label form-control", label: "New comment or review" %>
  <%= f.button :submit, "Post", class: "btn btn-cocktail" %>
<% end %>